{{ if .Values.global.gcp.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: otterize-credentials-operator-gcp-mutating-webhook-configuration
  labels:
    app.kubernetes.io/part-of: otterize
    app.kubernetes.io/component: credentials-operator
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app.kubernetes.io/version: {{ .Chart.Version }}
webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      service:
        name: credentials-operator-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-gcp-v1-pod
        port: 9443
    failurePolicy: Ignore
    name: gcp.pods.credentials-operator.otterize.com
    objectSelector:
      matchLabels:
        "credentials-operator.otterize.com/create-gcp-sa": "true"
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
    sideEffects: NoneOnDryRun
{{ end }}