{{ if .Values.global.azure.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: otterize-credentials-operator-azure-mutating-webhook-configuration
  labels:
    {{ include "shared_labels" . | nindent 4 }}
    app.kubernetes.io/component: credentials-operator-azure-mutating-webhook
  annotations:
    {{ include "shared_annotations" . | nindent 4 }}
webhooks:
  - admissionReviewVersions:
    - v1
    clientConfig:
      service:
        name: credentials-operator-webhook-service
        namespace: '{{ .Release.Namespace }}'
        path: /mutate-azure-v1-pod
        port: 9443
    failurePolicy: Ignore
    name: azure.pods.credentials-operator.otterize.com
    objectSelector:
      matchLabels:
        "credentials-operator.otterize.com/create-azure-workload-identity": "true"
    rules:
    - apiGroups:
      - ""
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - pods
    sideEffects: NoneOnDryRun
{{ end }}