{{ if .Values.istiowatcher.enable }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "otterize.istiowatcher.fullName" . }}
  labels:
    {{- with .Values.global.commonLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.global.commonAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "otterize.istiowatcher.fullName" . }}
  template:
    metadata:
      labels:
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: {{ template "otterize.istiowatcher.fullName" . }}
      annotations:
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      securityContext:
        runAsNonRoot: true
      {{ if .Values.istiowatcher.pullSecrets }}
      imagePullSecrets:
        - name: {{ .Values.istiowatcher.pullSecrets }}
      {{ end }}
      containers:
        - name: {{ template "otterize.istiowatcher.fullName" . }}
          image: "{{ .Values.istiowatcher.repository }}/{{ .Values.istiowatcher.image }}:{{ default $.Chart.AppVersion .Values.istiowatcher.tag }}"
          {{ if .Values.istiowatcher.pullPolicy }}
          imagePullPolicy: {{ .Values.istiowatcher.pullPolicy }}
          {{ end }}
          resources:
            {{- toYaml .Values.istiowatcher.resources | nindent 12 }}
          env:
            - name: OTTERIZE_MAPPER_API_URL
              value: http://{{ template "otterize.mapper.fullName" . }}:9090/query
            - name: OTTERIZE_DEBUG
              value: {{ .Values.debug | quote }}
      serviceAccountName: {{ template "otterize.istiowatcher.fullName" . }}
{{ end }}